[package]
name = "image_viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
makepad-widgets = { git = "https://github.com/wyeworks/makepad", branch = "moly" }
moly-kit = { git = "https://github.com/moxin-org/moly.git", features = ["full"], branch = "main" }
